Version Reproductible & Propre du précédent code "fusions_data".

à faire: réorganiser le Git: 

beau readme
librairies à installer
ce que le projet nous a appris

data/ 
    raw_Insee/
    raw_elections/
    merged/

notebooks/
    data_preparation (python pandas)
    analyse_modelisation (regression statsmodel)
    vizualisation (geopandas)

fct/
    si des fonctions python a appeller



STANDARDISER LES VARIABLES
vérifier les path de chaque code (j'ai renommé certains path pour y voir plus clair)

LE FICHIER DE SORTIE EST DISPONIBLE SUR LE GIT. MAIS CE CODE LE GENERE SI BESOIN (pour vérifier la réplicabilité par exemple si vous le souhaitez!)

In [151]:
import pandas as pd
import numpy as np
import os

# Récupère le dossier où se trouve ce notebook
NOTEBOOK_DIR = os.getcwd()

# '..' remonte d'un cran pour accéder au dossier data, puis sous dossiers Insee et elections
RAW_INSEE_DIR = os.path.join(NOTEBOOK_DIR, '..', 'data', 'raw_Insee')
RAW_ELEC_DIR = os.path.join(NOTEBOOK_DIR, '..', 'data', 'raw_elections')
# On remplace 'processed' par 'merged'
MERGED_DATA_DIR = os.path.join(NOTEBOOK_DIR, '..', 'data', 'merged')

# On vérifie que le dossier de sortie existe, sinon on le crée
os.makedirs(MERGED_DATA_DIR, exist_ok=True)

print(f"OK Source INSEE : {RAW_INSEE_DIR}")
print(f"OK Source Élections : {RAW_ELEC_DIR}")
print(f"OK Destination : {MERGED_DATA_DIR}")

OK Source INSEE : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/raw_Insee
OK Source Élections : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/raw_elections
OK Destination : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/merged

In [152]:
# Dictionnaire des fichiers raw INSEE
FILES_INSEE = {
    'pop_2022': 'population_2022.xlsx',
    'pop_2020': 'population_2020.CSV',
    'pop_2017': 'population_2017.xlsx',
    'pop_2014': 'population_2014.xls',
    'diplo_2022': 'diplome_2022.xlsx',
    'diplo_2020': 'diplome_2020.CSV',
    'diplo_2017': 'diplome_2017.xlsx',
    'diplo_2014': 'diplome_2014.xls',
    'rev_2021': 'revenu_2021.xlsx',
    'rev_2019': 'revenu_2019.csv',
    'rev_2016': 'revenu_2016.xls',
    'rev_2013': 'revenu_2013.xls'
}



# POPULATION & CADRES
# rq: en-têtes pour excel Insee (header=5)
df_pop_2022 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2022']), header=5, dtype={'COM': str})
df_pop_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2020']), sep=';', dtype={'COM': str})
df_pop_2017 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2017']), header=5, dtype={'COM': str})
df_pop_2014 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2014']), header=5, dtype={'COM': str})

# DIPLÔMES
df_diplo_2022 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2022']), header=5, dtype={'CODGEO': str})
df_diplo_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2020']), sep=';', header=0, dtype={'COM': str})
df_diplo_2017 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2017']), header=5, dtype={'CODGEO': str})
df_diplo_2014 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2014']), header=5, dtype={'CODGEO': str})
# REVENUS
# bug avec ce fichier: df_rev_2021 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['rev_2021']), header=4, dtype={'CODGEO': str})
df_rev_2019 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['rev_2019']), sep=';', dtype={'CODGEO': str})
df_rev_2016 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['rev_2016']), header=5, dtype={'CODGEO': str})
df_rev_2013 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['rev_2013']), header=5, dtype={'CODGEO': str})

print("Données chargées.")

/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_44201/712927208.py:22: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pop_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2020']), sep=';', dtype={'COM': str})
/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_44201/712927208.py:28: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_diplo_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2020']), sep=';', header=0, dtype={'COM': str})

Données chargées.

Cellule de visualisation (réservée aux .head() )

In [153]:
df_pop_2022.columns
# C22_POP15P_CS3 remplacé par C22_POP15P_STAT_GSEC13_23

Index(['IRIS', 'REG', 'DEP', 'UU2020', 'COM', 'LIBCOM', 'TRIRIS', 'GRD_QUART',
       'LIBIRIS', 'TYP_IRIS', 'LAB_IRIS', 'P22_POP', 'P22_POP0002',
       'P22_POP0305', 'P22_POP0610', 'P22_POP1117', 'P22_POP1824',
       'P22_POP2539', 'P22_POP4054', 'P22_POP5564', 'P22_POP6579',
       'P22_POP80P', 'P22_POP0014', 'P22_POP1529', 'P22_POP3044',
       'P22_POP4559', 'P22_POP6074', 'P22_POP75P', 'P22_POP0019',
       'P22_POP2064', 'P22_POP65P', 'P22_POPH', 'P22_H0014', 'P22_H1529',
       'P22_H3044', 'P22_H4559', 'P22_H6074', 'P22_H75P', 'P22_H0019',
       'P22_H2064', 'P22_H65P', 'P22_POPF', 'P22_F0014', 'P22_F1529',
       'P22_F3044', 'P22_F4559', 'P22_F6074', 'P22_F75P', 'P22_F0019',
       'P22_F2064', 'P22_F65P', 'C22_POP15P', 'C22_POP15P_STAT_GSEC11_21',
       'C22_POP15P_STAT_GSEC12_22', 'C22_POP15P_STAT_GSEC13_23',
       'C22_POP15P_STAT_GSEC14_24', 'C22_POP15P_STAT_GSEC15_25',
       'C22_POP15P_STAT_GSEC16_26', 'C22_POP15P_STAT_GSEC32',
       'C22_POP15P_STAT_GSEC40', 'C22_H15P', 'C22_H15P_STAT_GSEC11_21',
       'C22_H15P_STAT_GSEC12_22', 'C22_H15P_STAT_GSEC13_23',
       'C22_H15P_STAT_GSEC14_24', 'C22_H15P_STAT_GSEC15_25',
       'C22_H15P_STAT_GSEC16_26', 'C22_H15P_STAT_GSEC32',
       'C22_H15P_STAT_GSEC40', 'C22_F15P', 'C22_F15P_STAT_GSEC11_21',
       'C22_F15P_STAT_GSEC12_22', 'C22_F15P_STAT_GSEC13_23',
       'C22_F15P_STAT_GSEC14_24', 'C22_F15P_STAT_GSEC15_25',
       'C22_F15P_STAT_GSEC16_26', 'C22_F15P_STAT_GSEC32',
       'C22_F15P_STAT_GSEC40', 'P22_POP_FR', 'P22_POP_ETR', 'P22_POP_IMM',
       'P22_PMEN', 'P22_PHORMEN'],
      dtype='object')

A FAIRE: resoudre le probleme de log(0)

In [154]:
# Transformation des données socio-démographiques

# Population & cadres
# 2020
# On groupe par COM et on somme pour éviter les doublons (cas où le fichier source est segmenté par âge/sexe)
pop20 = df_pop_2020.groupby('COM')[['P20_POP', 'C20_POP15P_CS3']].sum().reset_index()
pop20.columns = ['COM', 'pop_2020', 'cadres_nb_2020']

pop22 = df_pop_2022.groupby('COM')[['P22_POP', 'C22_POP15P_STAT_GSEC13_23']].sum().reset_index()
pop22.columns = ['COM', 'pop_2022', 'cadres_nb_2022']

pop17 = df_pop_2017.groupby('COM')[['P17_POP', 'C17_POP15P_CS3']].sum().reset_index()
pop17.columns = ['COM', 'pop_2017', 'cadres_nb_2017']

# 2014 (Attention INSEE change parfois COM en CODGEO, ici on assure)
pop14 = df_pop_2014.groupby('COM')[['P14_POP', 'C14_POP15P_CS3']].sum().reset_index()
pop14.columns = ['COM', 'pop_2014', 'cadres_nb_2014']

# Diplomes

# 2020 : Il faut sommer les colonnes (Sup court + Sup long...) pour se rabaisser à la definition de 2014 qui est vulgairement agrégée
df_diplo_2020['sup_nb_2020'] = (
    df_diplo_2020['P20_NSCOL15P_SUP2'] + 
    df_diplo_2020['P20_NSCOL15P_SUP34'] + 
    df_diplo_2020['P20_NSCOL15P_SUP5']
)
# On groupe aussi ici pour avoir une ligne par commune
dip20 = df_diplo_2020.groupby('COM')['sup_nb_2020'].sum().reset_index()

#2022 
df_diplo_2022['sup_nb_2022'] = (
    df_diplo_2022['P22_NSCOL15P_SUP2'] + 
    df_diplo_2022['P22_NSCOL15P_SUP34'] + 
    df_diplo_2022['P22_NSCOL15P_SUP5']
)
dip22 = df_diplo_2022.groupby('CODGEO')['sup_nb_2022'].sum().reset_index()
dip22.columns = ['COM', 'sup_nb_2022']

# 2017 
df_diplo_2017['sup_nb_2017'] = (
    df_diplo_2017['P17_NSCOL15P_SUP2'] + 
    df_diplo_2017['P17_NSCOL15P_SUP34'] + 
    df_diplo_2017['P17_NSCOL15P_SUP5']
)
dip17 = df_diplo_2017.groupby('CODGEO')['sup_nb_2017'].sum().reset_index()
dip17.columns = ['COM', 'sup_nb_2017']

# 2014
dip14 = df_diplo_2014.groupby('CODGEO')['P14_NSCOL15P_SUP'].sum().reset_index()
dip14.columns = ['COM', 'sup_nb_2014']

# Revenus
# On s'assure d'avoir des valeurs numériques et une seule ligne par commune (drop_duplicates) car on ne somme pas des médianes
df_rev_2019['MED19'] = pd.to_numeric(df_rev_2019['MED19'], errors='coerce')
rev19 = df_rev_2019[['CODGEO', 'MED19']].drop_duplicates(subset='CODGEO').rename(columns={'CODGEO': 'COM', 'MED19': 'med_2019'})

df_rev_2016['MED16'] = pd.to_numeric(df_rev_2016['MED16'], errors='coerce')
rev16 = df_rev_2016[['CODGEO', 'MED16']].drop_duplicates(subset='CODGEO').rename(columns={'CODGEO': 'COM', 'MED16': 'med_2016'})

df_rev_2013['MED13'] = pd.to_numeric(df_rev_2013['MED13'], errors='coerce')
rev13 = df_rev_2013[['CODGEO', 'MED13']].drop_duplicates(subset='CODGEO').rename(columns={'CODGEO': 'COM', 'MED13': 'med_2013'})

# Fusion globale des données socio-démographiques

# On part de la population 2020 comme base
df_socio = pop20.merge(pop14, on='COM', how='inner')
df_socio = df_socio.merge(pop22, on='COM', how='left')
df_socio = df_socio.merge(pop17, on='COM', how='left')
df_socio = df_socio.merge(dip22, on='COM', how='left')
df_socio = df_socio.merge(dip17, on='COM', how='left')
df_socio = df_socio.merge(dip20, on='COM', how='left')
df_socio = df_socio.merge(dip14, on='COM', how='left')
df_socio = df_socio.merge(rev19, on='COM', how='left')
df_socio = df_socio.merge(rev16, on='COM', how='left')
df_socio = df_socio.merge(rev13, on='COM', how='left')

# problème possible log(0): on résout, ainsi que secret statistique et NaN pour les revenus

# Transforme les 's' (secret statistique) en NaN (déjà géré plus haut pour être sûr, mais on garde ta logique)
df_socio['med_2013'] = pd.to_numeric(df_socio['med_2013'], errors='coerce')
df_socio['med_2019'] = pd.to_numeric(df_socio['med_2019'], errors='coerce')
df_socio['med_2016'] = pd.to_numeric(df_socio['med_2016'], errors='coerce')

#  Supprime les lignes avec un revenu ou une population de 0
df_socio = df_socio[(df_socio['med_2013'] > 0) & (df_socio['med_2016'] > 0) & (df_socio['med_2019'] > 0) & (df_socio['pop_2014'] > 0) & (df_socio['pop_2020'] > 0) & (df_socio['pop_2017'] > 0) & (df_socio['pop_2022'] > 0)]


# Calcul des variables Delta

# Croissance Pop (Log-diff)
df_socio['croissance_pop_14_20'] = np.log(df_socio['pop_2020']) - np.log(df_socio['pop_2014'])
# Croissance Pop 2017-2022 (Log-diff)
df_socio['croissance_pop_17_22'] = np.log(df_socio['pop_2022']) - np.log(df_socio['pop_2017'])

#  Delta Diplômés (Variation en  %)
df_socio['pct_sup_2022'] = df_socio['sup_nb_2022'] / df_socio['pop_2022']
df_socio['pct_sup_2020'] = df_socio['sup_nb_2020'] / df_socio['pop_2020']
df_socio['pct_sup_2017'] = df_socio['sup_nb_2017'] / df_socio['pop_2017']
df_socio['delta_pct_diplome_17_22'] = df_socio['pct_sup_2022'] - df_socio['pct_sup_2017']
df_socio['pct_sup_2014'] = df_socio['sup_nb_2014'] / df_socio['pop_2014']
df_socio['delta_pct_diplome_14_20'] = df_socio['pct_sup_2020'] - df_socio['pct_sup_2014']

# Delta Cadres (Variation  %) (On oublie, diplomes racontent globalement la même chose... mais on le met quand même)
df_socio['pct_cadres_2022'] = df_socio['cadres_nb_2022'] / df_socio['pop_2022']
df_socio['pct_cadres_2017'] = df_socio['cadres_nb_2017'] / df_socio['pop_2017']
df_socio['delta_pct_cadres_17_22'] = df_socio['pct_cadres_2022'] - df_socio['pct_cadres_2017']
df_socio['pct_cadres_2020'] = df_socio['cadres_nb_2020'] / df_socio['pop_2020']
df_socio['pct_cadres_2014'] = df_socio['cadres_nb_2014'] / df_socio['pop_2014']
df_socio['delta_pct_cadres_14_20'] = df_socio['pct_cadres_2020'] - df_socio['pct_cadres_2014']

# Richesse initiale (Log)
df_socio['log_med_13'] = np.log(df_socio['med_2013'])

 # richesse en 2016
df_socio['log_med_16'] = np.log(df_socio['med_2016'])

# Richesse en 2019
df_socio['log_med_19'] = np.log(df_socio['med_2019'])   

print(f"Base socio-démo prête : {df_socio.shape[0]} communes.")

Base socio-démo prête : 31011 communes.

In [155]:
df_socio.head(20)

,COM,pop_2020,cadres_nb_2020,pop_2014,cadres_nb_2014,pop_2022,cadres_nb_2022,pop_2017,cadres_nb_2017,sup_nb_2022,...,delta_pct_diplome_14_20,pct_cadres_2022,pct_cadres_2017,delta_pct_cadres_17_22,pct_cadres_2020,pct_cadres_2014,delta_pct_cadres_14_20,log_med_13,log_med_16,log_med_19
0,01001,806.0,61.774238,767.0,75.000000,859.0,73.628571,776.0,75.875564,193.000000,...,0.040832,0.085714,0.097778,-0.012064,0.076643,0.097784,-0.021141,10.004689,10.029195,10.084558
1,01002,262.0,18.283656,239.0,14.753086,273.0,19.854545,248.0,15.308642,85.000000,...,0.056232,0.072727,0.061728,0.010999,0.069785,0.061728,0.008057,10.052468,10.101604,10.070695
2,01004,14288.0,804.651500,14022.0,743.288479,15554.0,983.205730,14035.0,785.201502,3247.679791,...,0.035516,0.063212,0.055946,0.007266,0.056317,0.053009,0.003308,9.880935,9.889439,9.928668
3,01005,1782.0,115.000000,1627.0,105.518839,1917.0,135.089600,1689.0,109.858070,408.150328,...,0.038614,0.070469,0.065043,0.005426,0.064534,0.064855,-0.000321,10.016263,10.059551,10.087890
5,01007,2827.0,211.204367,2570.0,195.000000,2828.0,215.176435,2726.0,204.430108,622.392500,...,0.026414,0.076088,0.074993,0.001095,0.074710,0.075875,-0.001166,9.982792,10.005433,10.059636
6,01008,768.0,50.394579,743.0,71.903226,764.0,61.374188,752.0,49.801325,184.485905,...,0.015443,0.080333,0.066225,0.014108,0.065618,0.096774,-0.031156,10.071944,10.122374,10.144471
7,01009,324.0,4.773479,338.0,16.047478,335.0,13.543308,330.0,5.092593,83.611894,...,0.040404,0.040428,0.015432,0.024996,0.014733,0.047478,-0.032745,9.975168,10.047068,10.077021
8,01010,1101.0,44.135561,1142.0,42.731525,1150.0,19.628176,1115.0,45.000000,178.995358,...,0.021704,0.017068,0.040359,-0.023291,0.040087,0.037418,0.002669,9.953008,10.038043,10.076180
9,01011,368.0,34.615852,397.0,70.119481,399.0,48.233480,376.0,35.000000,98.841997,...,0.016317,0.120886,0.093085,0.027801,0.094065,0.176623,-0.082559,10.029680,10.053892,10.104385
10,01012,327.0,4.986798,325.0,33.440514,329.0,9.705870,326.0,5.000000,67.405138,...,-0.009456,0.029501,0.015337,0.014164,0.015250,0.102894,-0.087644,9.913982,9.960724,9.955606
11,01013,143.0,9.930556,157.0,7.850000,140.0,10.370370,144.0,10.000000,32.463768,...,-0.000694,0.074074,0.069444,0.004630,0.069444,0.050000,0.019444,9.879926,9.811592,9.898475
12,01014,3336.0,94.883670,3405.0,153.502860,3482.0,112.508825,3367.0,95.000000,542.975345,...,0.024956,0.032312,0.028215,0.004097,0.028442,0.045082,-0.016639,9.881534,9.911357,9.973946
13,01015,663.0,82.376950,638.0,24.399073,688.0,46.723394,644.0,79.629057,190.603419,...,0.044673,0.067912,0.123648,-0.055736,0.124249,0.038243,0.086006,9.979853,10.014895,10.030120
14,01016,458.0,15.000000,440.0,19.426049,459.0,4.729020,463.0,20.493397,75.059107,...,0.029098,0.010303,0.044262,-0.033959,0.032751,0.044150,-0.011399,9.929764,9.923582,9.991498
15,01017,445.0,0.000000,427.0,4.874429,420.0,0.000000,442.0,4.985744,73.000000,...,0.046510,0.000000,0.011280,-0.011280,0.000000,0.011416,-0.011416,9.833321,9.843260,9.909470
17,01021,1490.0,141.581345,1376.0,99.237497,1513.0,145.478995,1408.0,132.394737,414.974158,...,0.037965,0.096153,0.094030,0.002122,0.095021,0.072120,0.022901,10.041538,10.049873,10.119002
18,01022,1213.0,41.185678,1193.0,30.253051,1141.0,40.251121,1237.0,30.185884,193.000000,...,0.044623,0.035277,0.024402,0.010875,0.033954,0.025359,0.008595,9.840654,9.895707,9.937406
20,01024,3299.0,192.812225,3386.0,152.424437,3372.0,166.908562,3211.0,185.000000,749.852188,...,0.032052,0.049498,0.057614,-0.008116,0.058446,0.045016,0.013430,9.966488,9.997758,10.035393
21,01025,4068.0,205.506844,3177.0,115.000000,4057.0,191.509453,4092.0,206.271695,797.523349,...,0.022329,0.047205,0.050409,-0.003204,0.050518,0.036198,0.014320,9.959330,9.997464,10.041944
22,01026,977.0,55.256873,881.0,20.000000,987.0,49.705917,923.0,51.917758,152.564648,...,0.018088,0.050361,0.056249,-0.005888,0.056558,0.022701,0.033856,9.930422,9.938951,9.955131

In [156]:
# CHARGEMENT ELECTIONS


# VERIFIER bien CODE NUANCE et pas NUANCE LISTE
df_elec_14 = pd.read_csv(os.path.join(RAW_ELEC_DIR, 'elec_2014_all.csv'), dtype={'Code commune': str})
df_elec_20 = pd.read_csv(os.path.join(RAW_ELEC_DIR, 'elec_2020_all.csv'), dtype={'Code commune': str})


# Renommer si nécessaire (verifier Code Nuance)
df_elec_14 = df_elec_14.rename(columns={'Code commune': 'COM'})
df_elec_20 = df_elec_20.rename(columns={'Code commune': 'COM'})

# DÉFINITION DU BLOC GAUCHE + ÉCOLOS 

BLOC_GAUCHE = [
    'LVECE', 'LVEC', 'LECO',         # Écolos
    'LUG', 'LDVG', 'LSOC', 'LFI',    # Gauche diverse, PS, LFI
    'LGEN', 'LCOM', 'LRDG', 'LGRA', 'LPG' # PCF, Front de gauche, etc.
]

# Idée: mettr à 0 le score si pas de liste de gauche. C'est fait plus bas lors du merge

def calcul_score_bloc(df_elec, nuances_bloc, annee):
    """Calcule la somme des voix du bloc pour chaque commune."""
    # Filtrer les nuances du bloc (gauche dans notre cas)
    mask = df_elec['Code Nuance'].isin(nuances_bloc)
    df_filtered = df_elec[mask].copy()
    
    # Sommer par commune (cas où il y a >=2 listes de gauche)
    scores = df_filtered.groupby('COM')['% Voix/Exp'].sum().reset_index()
    scores.rename(columns={'% Voix/Exp': f'score_gauche_{annee}'}, inplace=True)
    return scores

# appel a la fction, calcul des scores
score_14 = calcul_score_bloc(df_elec_14, BLOC_GAUCHE, '2014')
score_20 = calcul_score_bloc(df_elec_20, BLOC_GAUCHE, '2020')

print("Scores calculés.")

Scores calculés.

In [157]:
# ELECTIONS PRESIDENTIELLES

df_elec_17_pres = pd.read_csv(os.path.join(RAW_ELEC_DIR, 'elec_2017_pres_all.csv'), dtype={'Code commune': str})
df_elec_22_pres = pd.read_csv(os.path.join(RAW_ELEC_DIR, 'elec_2022_pres_all.csv'), dtype={'Code commune': str})

# Définition des blocs 
gauche_2017 = ['MÉLENCHON', 'HAMON', 'POUTOU', 'ARTHAUD']
gauche_2022 = ['MÉLENCHON', 'JADOT', 'HIDALGO', 'ROUSSEL', 'POUTOU', 'ARTHAUD']

# pour 2017 

score_pres_17 = df_elec_17_pres[df_elec_17_pres['Nom'].isin(gauche_2017)] \
                .groupby('Code commune')['% Voix/Exp'].sum() \
                .reset_index(name='score_gauche_pres_2017')

# Pour 2022
score_pres_22 = df_elec_22_pres[df_elec_22_pres['Nom'].isin(gauche_2022)] \
                .groupby('Code commune')['% Voix/Exp'].sum() \
                .reset_index(name='score_gauche_pres_2022')

In [158]:
score_pres_22.head()

  Code commune  score_gauche_pres_2022
0        01001                   21.73
1        01002                   38.59
2        01004                   34.45
3        01005                   21.50
4        01006                   32.47

In [159]:
# On part de la base socio-demo (qui contient toutes les communes)
df_final = df_socio.copy()

# On colle les scores 2014
df_final = df_final.merge(score_14, on='COM', how='left')

# On colle les scores 2020
df_final = df_final.merge(score_20, on='COM', how='left')

df_final = df_final.merge(score_pres_17, left_on='COM', right_on='Code commune', how='left')
df_final = df_final.merge(score_pres_22, left_on='COM', right_on='Code commune', how='left')

# CRUCIAL pour la regression: Remplacer les NaN par 0
# Si pas de correspondance, ça veut dire 0 voix pour la gauche
df_final['score_gauche_2014'] = df_final['score_gauche_2014'].fillna(0)
df_final['score_gauche_2020'] = df_final['score_gauche_2020'].fillna(0)

# Calcul du DELTA SCORE (Variable Y)
df_final['delta_score_gauche_municipales'] = df_final['score_gauche_2020'] - df_final['score_gauche_2014']

df_final['delta_score_gauche_pres'] = df_final['score_gauche_pres_2022'] - df_final['score_gauche_pres_2017']

# Log population
# On le calcule ici tant que la population est brute (positive)
df_final['log_pop_2020'] = np.log(df_final['pop_2020'])
df_final['log_pop_2014'] = np.log(df_final['pop_2014'])
df_final['log_pop_2022'] = np.log(df_final['pop_2022'])
df_final['log_pop_2017'] = np.log(df_final['pop_2017'])

# Sélection des colonnes (pour R par exemple, analyse faite en R temporairement)
cols_export = [
    'COM',
    'score_gauche_2014',  
    'score_gauche_2020', 
    'score_gauche_pres_2017',
    'score_gauche_pres_2022',
    'delta_score_gauche_pres',
    'delta_score_gauche_municipales',
    'pop_2014',
    'pop_2017',
    'pop_2020', 
    'pop_2022',
    'log_pop_2014',
    'log_pop_2020',
    'log_pop_2017',
    'log_pop_2022',
    'croissance_pop_14_20',
    'croissance_pop_17_22', 
    'pct_sup_2014',
    'pct_sup_2017',
    'pct_sup_2020',
    'pct_sup_2022',
    'delta_pct_diplome_17_22',
    'delta_pct_diplome_14_20',
     
    'pct_cadres_2014',
    'pct_cadres_2017',
    'pct_cadres_2020',
    'pct_cadres_2022',
    'delta_pct_cadres_17_22',  
    'delta_pct_cadres_14_20', 
    'med_2013',
    'med_2019',  
    'med_2016',
    'log_med_16', 
    'log_med_13',
    'log_med_19' 

]

# On retire les lignes avec des NaN dans les variables explicatives (Socio-demo manquantes)
# faire analyse des données perdues ? 
df_export = df_final[cols_export].dropna()

print(f"Base finale prête : {len(df_export)} communes.")
print(df_export.head())

Base finale prête : 30717 communes.
     COM  score_gauche_2014  score_gauche_2020  score_gauche_pres_2017  \
0  01001               0.00                0.0                   19.40
1  01002               0.00                0.0                   28.42
2  01004              38.69                0.0                   29.24
3  01005               0.00                0.0                   19.08
4  01007              46.78                0.0                   26.10

   score_gauche_pres_2022  delta_score_gauche_pres  \
0                   21.73                     2.33
1                   38.59                    10.17
2                   34.45                     5.21
3                   21.50                     2.42
4                   26.52                     0.42

   delta_score_gauche_municipales  pop_2014  pop_2017  pop_2020  ...  \
0                            0.00     767.0     776.0     806.0  ...
1                            0.00     239.0     248.0     262.0  ...
2                          -38.69   14022.0   14035.0   14288.0  ...
3                            0.00    1627.0    1689.0    1782.0  ...
4                          -46.78    2570.0    2726.0    2827.0  ...

   pct_cadres_2020  pct_cadres_2022  delta_pct_cadres_17_22  \
0         0.076643         0.085714               -0.012064
1         0.069785         0.072727                0.010999
2         0.056317         0.063212                0.007266
3         0.064534         0.070469                0.005426
4         0.074710         0.076088                0.001095

   delta_pct_cadres_14_20      med_2013  med_2019      med_2016  log_med_16  \
0               -0.021141  22130.000000   23970.0  22679.000000   10.029195
1                0.008057  23213.000000   23640.0  24382.083333   10.101604
2                0.003308  19554.000000   20510.0  19721.000000    9.889439
3               -0.000321  22387.619048   24050.0  23378.000000   10.059551
4               -0.001166  21650.666667   23380.0  22146.451613   10.005433

   log_med_13  log_med_19
0   10.004689   10.084558
1   10.052468   10.070695
2    9.880935    9.928668
3   10.016263   10.087890
4    9.982792   10.059636

[5 rows x 35 columns]

In [160]:
df_export.columns

Index(['COM', 'score_gauche_2014', 'score_gauche_2020',
       'score_gauche_pres_2017', 'score_gauche_pres_2022',
       'delta_score_gauche_pres', 'delta_score_gauche_municipales', 'pop_2014',
       'pop_2017', 'pop_2020', 'pop_2022', 'log_pop_2014', 'log_pop_2020',
       'log_pop_2017', 'log_pop_2022', 'croissance_pop_14_20',
       'croissance_pop_17_22', 'pct_sup_2014', 'pct_sup_2017', 'pct_sup_2020',
       'pct_sup_2022', 'delta_pct_diplome_17_22', 'delta_pct_diplome_14_20',
       'pct_cadres_2014', 'pct_cadres_2017', 'pct_cadres_2020',
       'pct_cadres_2022', 'delta_pct_cadres_17_22', 'delta_pct_cadres_14_20',
       'med_2013', 'med_2019', 'med_2016', 'log_med_16', 'log_med_13',
       'log_med_19'],
      dtype='object')

expoort base de données pour regression présidentielles

In [161]:
# 1) standardisation des variables pour la regression présidentielles


# Standardisation des variables (X seulement)


df_std_presidentielles = df_export.copy()

# 1. On liste ce qu'on NE VEUT PAS toucher (Variable Cible Y + Identifiants)
# On garde Y naturel pour dire "ça augmente le vote de X points"
cols_excluded = ['COM', 'score_gauche_2014', 'score_gauche_2020', 'delta_score_gauche_pres', 'score_gauche_pres_2017', 'score_gauche_pres_2022', 'delta_score_gauche_municipales']

# 2. On récupère automatiquement toutes les autres variables numériques (les X)
# Cela inclura : croissance_pop, delta_pct_cadres, log_med_13, etc.
x_vars = [c for c in df_std_presidentielles.select_dtypes(include=['float', 'int']).columns if c not in cols_excluded]

print("Variables transformées (X) :", x_vars)
print("Variables conservées naturelles (Y) :", cols_excluded)

# 3. Standardisation (Z-score) des X
for col in x_vars:
    if df_std_presidentielles[col].std() != 0: # Sécurité
        df_std_presidentielles[col] = (df_std_presidentielles[col] - df_std_presidentielles[col].mean()) / df_std_presidentielles[col].std()



# 2) export

output_std_path = os.path.join(MERGED_DATA_DIR, 'data_regression_std_presidentielles.csv')
df_std_presidentielles.to_csv(output_std_path, index=False, sep=',', encoding='utf-8', na_rep='NA')

print(f"Fichier prêt pour l'analyse : {output_std_path}")

Variables transformées (X) : ['pop_2014', 'pop_2017', 'pop_2020', 'pop_2022', 'log_pop_2014', 'log_pop_2020', 'log_pop_2017', 'log_pop_2022', 'croissance_pop_14_20', 'croissance_pop_17_22', 'pct_sup_2014', 'pct_sup_2017', 'pct_sup_2020', 'pct_sup_2022', 'delta_pct_diplome_17_22', 'delta_pct_diplome_14_20', 'pct_cadres_2014', 'pct_cadres_2017', 'pct_cadres_2020', 'pct_cadres_2022', 'delta_pct_cadres_17_22', 'delta_pct_cadres_14_20', 'med_2013', 'med_2019', 'med_2016', 'log_med_16', 'log_med_13', 'log_med_19']
Variables conservées naturelles (Y) : ['COM', 'score_gauche_2014', 'score_gauche_2020', 'delta_score_gauche_pres', 'score_gauche_pres_2017', 'score_gauche_pres_2022', 'delta_score_gauche_municipales']
Fichier prêt pour l'analyse : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/merged/data_regression_std_presidentielles.csv

Problème majeur: la politique n'est pas forcément bien "structurée" pour toutes les communes, notamment pas pour les communes de peu d'habitants. Ainsi l'analyse ne peut proter que sur les communes dont la politique est "structurée": elle ne represente donc pas une étude poltiique de toute la France.

In [162]:
# On crée un filtre : au moins un score > 0 en 2014 OU en 2020 
filter_structural = (df_export['score_gauche_2014'] > 0) | (df_export['score_gauche_2020'] > 0)

# On filtre
df_reg_municipales = df_export[filter_structural].copy()

print(f"Nombre de communes pour la régression : {df_reg_municipales.shape[0]}")

Nombre de communes pour la régression : 1532

In [164]:
print(31069-1533,"communes sont exclues de l'analyse car politique jugée pas assez structurée pour une régression viable.", "Il reste donc",1533,"communes pour l'analyse.")

29536 communes sont exclues de l'analyse car politique jugée pas assez structurée pour une régression viable. Il reste donc 1533 communes pour l'analyse.

Regarder aussi communes de plus de "arbitraire,1500-3500" habs pour analyse socio pertinente ? Regarder présidentielles ?

Cellule de visualisation (réservée aux .head() ) pour vérifier la cohérence

In [165]:
df_reg_municipales.head()

,COM,score_gauche_2014,score_gauche_2020,score_gauche_pres_2017,score_gauche_pres_2022,delta_score_gauche_pres,delta_score_gauche_municipales,pop_2014,pop_2017,pop_2020,...,pct_cadres_2020,pct_cadres_2022,delta_pct_cadres_17_22,delta_pct_cadres_14_20,med_2013,med_2019,med_2016,log_med_16,log_med_13,log_med_19
2,01004,38.69,0.0,29.24,34.45,5.21,-38.69,14022.0,14035.0,14288.0,...,0.056317,0.063212,0.007266,0.003308,19554.000000,20510.0,19721.000000,9.889439,9.880935,9.928668
4,01007,46.78,0.0,26.10,26.52,0.42,-46.78,2570.0,2726.0,2827.0,...,0.074710,0.076088,0.001095,-0.001166,21650.666667,23380.0,22146.451613,10.005433,9.982792,10.059636
27,01034,48.83,0.0,26.42,31.85,5.43,-48.83,8983.0,9103.0,9207.0,...,0.038647,0.039785,0.001960,0.000969,18549.000000,20030.0,18818.000000,9.842569,9.828171,9.904986
134,01160,49.55,0.0,29.70,40.07,10.37,-49.55,9337.0,9766.0,10612.0,...,0.134421,0.194857,0.059915,-0.026035,25508.333333,26770.0,26579.333333,10.187889,10.146760,10.195037
151,01185,38.72,0.0,29.42,31.71,2.29,-38.72,3829.0,4853.0,4824.0,...,0.046021,0.047081,0.017269,0.023136,20198.148148,21990.0,21040.500000,9.954204,9.913346,9.998343

STANDARDISATION (ne changera ni le R^2n ni les t-values, ni les p-values,  mais rendra les coeffs beaucoup plus faciles à interpréter) (rendra les coeffs corrects surtout!) méthode: Z-score.

In [166]:
# Standardisation des variables (X seulement)


df_std_municipales = df_reg_municipales.copy()

# 1. On liste ce qu'on NE VEUT PAS toucher (Variable Cible Y + Identifiants)
# On garde Y naturel pour dire "ça augmente le vote de X points"
cols_excluded = ['COM', 'score_gauche_2014', 'score_gauche_2020', 'delta_score_gauche_pres', 'score_gauche_pres_2017', 'score_gauche_pres_2022', 'delta_score_gauche_municipales']

# 2. On récupère automatiquement toutes les autres variables numériques (les X)
# Cela inclura : croissance_pop, delta_pct_cadres, log_med_13, etc.
x_vars = [c for c in df_std_municipales.select_dtypes(include=['float', 'int']).columns if c not in cols_excluded]

print("Variables transformées (X) :", x_vars)
print("Variables conservées naturelles (Y) :", cols_excluded)

# 3. Standardisation (Z-score) des X
for col in x_vars:
    if df_std_municipales[col].std() != 0: # Sécurité
        df_std_municipales[col] = (df_std_municipales[col] - df_std_municipales[col].mean()) / df_std_municipales[col].std()

# 4. Export
output_std_path = os.path.join(MERGED_DATA_DIR, 'data_regression_std.csv')
df_std_municipales.to_csv(output_std_path, index=False, sep=',', encoding='utf-8', na_rep='NA')

print(f"Fichier prêt pour l'analyse : {output_std_path}")

Variables transformées (X) : ['pop_2014', 'pop_2017', 'pop_2020', 'pop_2022', 'log_pop_2014', 'log_pop_2020', 'log_pop_2017', 'log_pop_2022', 'croissance_pop_14_20', 'croissance_pop_17_22', 'pct_sup_2014', 'pct_sup_2017', 'pct_sup_2020', 'pct_sup_2022', 'delta_pct_diplome_17_22', 'delta_pct_diplome_14_20', 'pct_cadres_2014', 'pct_cadres_2017', 'pct_cadres_2020', 'pct_cadres_2022', 'delta_pct_cadres_17_22', 'delta_pct_cadres_14_20', 'med_2013', 'med_2019', 'med_2016', 'log_med_16', 'log_med_13', 'log_med_19']
Variables conservées naturelles (Y) : ['COM', 'score_gauche_2014', 'score_gauche_2020', 'delta_score_gauche_pres', 'score_gauche_pres_2017', 'score_gauche_pres_2022', 'delta_score_gauche_municipales']
Fichier prêt pour l'analyse : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/merged/data_regression_std.csv

In [167]:

#export des données brutes non standardisées

output_filename = 'data_regression.csv'
output_path = os.path.join(MERGED_DATA_DIR, output_filename)

df_reg_municipales.to_csv(
    output_path, 
    index=False, 
    sep=',', 
    encoding='utf-8', 
    na_rep='NA' # Pour compatibilité R
)

print(f"Fichier exporté avec succès : {output_path}")

Fichier exporté avec succès : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/merged/data_regression.csv