Version Reproductible & Propre du précédent code "fusions_data".

à faire: réorganiser le Git: 

beau readme
librairies à installer
ce que le projet nous a appris

data/ 
    raw_Insee/
    raw_elections/
    merged/

notebooks/
    data_preparation (python pandas)
    analyse_modelisation (regression statsmodel)
    vizualisation (geopandas)

fct/
    si des fonctions python a appeller



STANDARDISER LES VARIABLES
vérifier les path de chaque code (j'ai renommé certains path pour y voir plus clair)

LE FICHIER DE SORTIE EST DISPONIBLE SUR LE GIT. MAIS CE CODE LE GENERE SI BESOIN (pour vérifier la réplicabilité par exemple si vous le souhaitez!)

In [87]:
import pandas as pd
import numpy as np
import os

# Récupère le dossier où se trouve ce notebook
NOTEBOOK_DIR = os.getcwd()

# '..' remonte d'un cran pour accéder au dossier data, puis sous dossiers Insee et elections
RAW_INSEE_DIR = os.path.join(NOTEBOOK_DIR, '..', 'data', 'raw_Insee')
RAW_ELEC_DIR = os.path.join(NOTEBOOK_DIR, '..', 'data', 'raw_elections')
# On remplace 'processed' par 'merged'
MERGED_DATA_DIR = os.path.join(NOTEBOOK_DIR, '..', 'data', 'merged')

# On vérifie que le dossier de sortie existe, sinon on le crée
os.makedirs(MERGED_DATA_DIR, exist_ok=True)

print(f"OK Source INSEE : {RAW_INSEE_DIR}")
print(f"OK Source Élections : {RAW_ELEC_DIR}")
print(f"OK Destination : {MERGED_DATA_DIR}")

OK Source INSEE : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/raw_Insee
OK Source Élections : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/raw_elections
OK Destination : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/merged

In [88]:
# Dictionnaire des fichiers raw INSEE
FILES_INSEE = {
    'pop_2020': 'population_2020.CSV',
    'pop_2014': 'population_2014.xls',
    'diplo_2020': 'diplome_2020.CSV',
    'diplo_2014': 'diplome_2014.xls',
    'rev_2019': 'revenu_2019.csv',
    'rev_2013': 'revenu_2013.xls'
}



# POPULATION & CADRES
# rq: en-têtes pour excel Insee (header=5)
df_pop_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2020']), sep=';', dtype={'COM': str})
df_pop_2014 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2014']), header=5, dtype={'COM': str})

# DIPLÔMES
df_diplo_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2020']), sep=';', header=0, dtype={'COM': str})
df_diplo_2014 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2014']), header=5, dtype={'CODGEO': str})
# REVENUS
df_rev_2019 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['rev_2019']), sep=';', dtype={'CODGEO': str})
df_rev_2013 = pd.read_excel(os.path.join(RAW_INSEE_DIR, FILES_INSEE['rev_2013']), header=5, dtype={'CODGEO': str})

print("Données chargées.")

/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_44201/322832310.py:15: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pop_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['pop_2020']), sep=';', dtype={'COM': str})
/var/folders/47/r5kv9z4j6kg1sk0dvr2l5ydh0000gn/T/ipykernel_44201/322832310.py:19: DtypeWarning: Columns (0,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_diplo_2020 = pd.read_csv(os.path.join(RAW_INSEE_DIR, FILES_INSEE['diplo_2020']), sep=';', header=0, dtype={'COM': str})

Données chargées.

Cellule de visualisation (réservée aux .head() )

In [89]:
df_pop_2020.head(20)

,IRIS,COM,TYP_IRIS,LAB_IRIS,P20_POP,P20_POP0002,P20_POP0305,P20_POP0610,P20_POP1117,P20_POP1824,...,C20_F15P_CS4,C20_F15P_CS5,C20_F15P_CS6,C20_F15P_CS7,C20_F15P_CS8,P20_POP_FR,P20_POP_ETR,P20_POP_IMM,P20_PMEN,P20_PHORMEN
0,10010000,01001,Z,5,806.000000,31.484313,26.911746,53.754190,77.438835,28.293681,...,46.590055,79.695680,28.079284,82.546801,28.071601,796.562592,9.437408,17.783541,806.000000,0.000000
1,10020000,01002,Z,5,262.000000,5.988437,12.166343,19.185203,34.218154,11.595410,...,24.305648,14.371604,4.493918,22.196847,4.493918,260.981319,1.018681,2.761700,262.000000,0.000000
2,10040101,01004,H,1,1805.376610,80.347443,44.940185,98.034462,132.206137,350.595992,...,102.223408,239.751222,51.887787,169.925225,186.025416,1550.387323,254.989286,213.675617,1442.383120,362.993490
3,10040102,01004,H,1,3633.137558,151.531803,133.872557,207.372432,257.669740,376.985965,...,180.432551,402.975969,154.584388,420.664788,310.793231,3170.910863,462.226695,575.389845,3633.137558,0.000000
4,10040201,01004,H,1,4097.728721,165.340974,169.880658,243.321681,360.778807,327.817455,...,254.897967,396.638516,170.174486,529.191909,323.199708,3690.082310,407.646411,424.023175,4009.730299,87.998422
5,10040202,01004,H,1,4751.757111,153.751141,186.444716,319.865260,461.632363,294.816387,...,366.443598,429.109321,134.712896,537.641133,372.659811,4554.685863,197.071248,382.470417,4701.758008,49.999103
6,10050000,01005,Z,5,1782.000000,63.000000,69.000000,125.000000,157.000000,101.000000,...,115.000000,250.000000,20.000000,185.000000,80.000000,1749.000000,33.000000,73.000000,1782.000000,0.000000
7,10060000,01006,Z,5,113.000000,2.973684,2.973684,3.964912,1.982456,5.947368,...,0.000000,14.868421,4.956140,9.912281,0.000000,109.035088,3.964912,3.964912,113.000000,0.000000
8,10070000,01007,Z,5,2827.000000,116.129773,111.845504,221.523484,280.653166,142.292168,...,232.838955,318.671552,70.638058,225.103608,176.106539,2770.835399,56.164601,102.013341,2817.000090,9.999910
9,10080000,01008,Z,5,768.000000,21.161093,28.094502,48.160740,69.216441,52.423992,...,70.547686,86.746483,25.638031,67.217211,25.502495,749.805263,18.194737,25.330477,768.000000,0.000000
10,10090000,01009,Z,5,324.000000,4.810169,7.674257,18.952590,30.850680,17.597934,...,45.021826,39.881448,0.000000,41.575061,14.694386,314.231492,9.768508,13.886450,324.000000,0.000000
11,10100000,01010,Z,5,1101.000000,40.608398,47.787948,99.370044,103.806966,46.030514,...,38.972938,148.588059,50.463338,94.019520,62.473681,1068.265548,32.734452,58.661526,1101.000000,0.000000
12,10110000,01011,Z,5,368.000000,14.064795,14.203463,32.656142,35.894328,10.702579,...,24.033565,19.650810,0.000000,51.158724,14.389763,361.043868,6.956132,7.939680,368.000000,0.000000
13,10120000,01012,Z,5,327.000000,9.068663,13.078886,20.164919,34.250117,11.036403,...,15.049648,40.177613,5.016535,54.973594,10.009236,321.989422,5.010578,8.011565,325.002919,1.997081
14,10130000,01013,Z,5,143.000000,6.951389,5.958333,8.937500,10.923611,6.951389,...,4.965278,19.861111,4.965278,4.965278,9.930556,143.000000,0.000000,1.986111,143.000000,0.000000
15,10140000,01014,Z,5,3336.000000,83.744084,100.274328,243.894297,315.604086,193.254184,...,134.407077,251.202590,132.067212,518.364359,276.359923,2884.309716,451.690284,768.316230,3292.996697,43.003303
16,10150000,01015,Z,5,663.000000,16.304612,16.219313,36.444485,57.815119,39.711074,...,56.433983,61.403667,15.243744,98.385400,30.677780,652.688687,10.311313,20.565932,663.000000,0.000000
17,10160000,01016,Z,5,458.000000,10.000000,20.000000,35.000000,57.000000,14.000000,...,45.000000,45.000000,10.000000,65.000000,5.000000,447.000000,11.000000,15.000000,458.000000,0.000000
18,10170000,01017,Z,5,445.000000,14.821074,10.326138,36.371641,41.648680,22.502701,...,10.222866,60.729751,4.931375,68.107748,53.723020,428.420022,16.579978,22.479928,445.000000,0.000000
19,10190000,01019,Z,5,26.000000,0.000000,1.000000,2.000000,0.000000,2.000000,...,0.000000,0.000000,5.000000,10.000000,0.000000,24.000000,2.000000,3.000000,26.000000,0.000000

A FAIRE: resoudre le probleme de log(0)

In [90]:
# Transformation des données socio-démographiques

# Population & cadres
# 2020
# On groupe par COM et on somme pour éviter les doublons (cas où le fichier source est segmenté par âge/sexe)
pop20 = df_pop_2020.groupby('COM')[['P20_POP', 'C20_POP15P_CS3']].sum().reset_index()
pop20.columns = ['COM', 'pop_2020', 'cadres_nb_2020']

# 2014 (Attention INSEE change parfois COM en CODGEO, ici on assure)
pop14 = df_pop_2014.groupby('COM')[['P14_POP', 'C14_POP15P_CS3']].sum().reset_index()
pop14.columns = ['COM', 'pop_2014', 'cadres_nb_2014']

# Diplomes

# 2020 : Il faut sommer les colonnes (Sup court + Sup long...) pour se rabaisser à la definition de 2014 qui est vulgairement agrégée
df_diplo_2020['sup_nb_2020'] = (
    df_diplo_2020['P20_NSCOL15P_SUP2'] + 
    df_diplo_2020['P20_NSCOL15P_SUP34'] + 
    df_diplo_2020['P20_NSCOL15P_SUP5']
)
# On groupe aussi ici pour avoir une ligne par commune
dip20 = df_diplo_2020.groupby('COM')['sup_nb_2020'].sum().reset_index()

# 2014
dip14 = df_diplo_2014.groupby('CODGEO')['P14_NSCOL15P_SUP'].sum().reset_index()
dip14.columns = ['COM', 'sup_nb_2014']

# Revenus
# On s'assure d'avoir des valeurs numériques et une seule ligne par commune (drop_duplicates) car on ne somme pas des médianes
df_rev_2019['MED19'] = pd.to_numeric(df_rev_2019['MED19'], errors='coerce')
rev19 = df_rev_2019[['CODGEO', 'MED19']].drop_duplicates(subset='CODGEO').rename(columns={'CODGEO': 'COM', 'MED19': 'med_2019'})

df_rev_2013['MED13'] = pd.to_numeric(df_rev_2013['MED13'], errors='coerce')
rev13 = df_rev_2013[['CODGEO', 'MED13']].drop_duplicates(subset='CODGEO').rename(columns={'CODGEO': 'COM', 'MED13': 'med_2013'})

# Fusion globale des données socio-démographiques

# On part de la population 2020 comme base
df_socio = pop20.merge(pop14, on='COM', how='inner')
df_socio = df_socio.merge(dip20, on='COM', how='left')
df_socio = df_socio.merge(dip14, on='COM', how='left')
df_socio = df_socio.merge(rev19, on='COM', how='left')
df_socio = df_socio.merge(rev13, on='COM', how='left')

# problème possible log(0): on résout, ainsi que secret statistique et NaN pour les revenus

# Transforme les 's' (secret statistique) en NaN (déjà géré plus haut pour être sûr, mais on garde ta logique)
df_socio['med_2013'] = pd.to_numeric(df_socio['med_2013'], errors='coerce')
df_socio['med_2019'] = pd.to_numeric(df_socio['med_2019'], errors='coerce')

#  Supprime les lignes avec un revenu ou une population de 0
df_socio = df_socio[(df_socio['med_2013'] > 0) & (df_socio['med_2019'] > 0) & (df_socio['pop_2014'] > 0) & (df_socio['pop_2020'] > 0)]


# Calcul des variables Delta

# Croissance Pop (Log-diff)
df_socio['croissance_pop'] = np.log(df_socio['pop_2020']) - np.log(df_socio['pop_2014'])

#  Delta Diplômés (Variation en  %)
df_socio['pct_sup_2020'] = df_socio['sup_nb_2020'] / df_socio['pop_2020']
df_socio['pct_sup_2014'] = df_socio['sup_nb_2014'] / df_socio['pop_2014']
df_socio['delta_pct_diplome'] = df_socio['pct_sup_2020'] - df_socio['pct_sup_2014']

# Delta Cadres (Variation  %)
df_socio['pct_cadres_2020'] = df_socio['cadres_nb_2020'] / df_socio['pop_2020']
df_socio['pct_cadres_2014'] = df_socio['cadres_nb_2014'] / df_socio['pop_2014']
df_socio['delta_pct_cadres'] = df_socio['pct_cadres_2020'] - df_socio['pct_cadres_2014']

# Richesse initiale (Log)
df_socio['log_med_13'] = np.log(df_socio['med_2013'])

# Richesse en 2019
df_socio['log_med_19'] = np.log(df_socio['med_2019'])   

print(f"Base socio-démo prête : {df_socio.shape[0]} communes.")

Base socio-démo prête : 31114 communes.

In [91]:
df_socio.head(20)

,COM,pop_2020,cadres_nb_2020,pop_2014,cadres_nb_2014,sup_nb_2020,sup_nb_2014,med_2019,med_2013,croissance_pop,pct_sup_2020,pct_sup_2014,delta_pct_diplome,pct_cadres_2020,pct_cadres_2014,delta_pct_cadres,log_med_13,log_med_19
0,01001,806.0,61.774238,767.0,75.000000,181.080438,141.000000,23970.0,22130.000000,0.049597,0.224666,0.183833,0.040832,0.076643,0.097784,-0.021141,10.004689,10.084558
1,01002,262.0,18.283656,239.0,14.753086,80.502440,59.995885,23640.0,23213.000000,0.091881,0.307261,0.251029,0.056232,0.069785,0.061728,0.008057,10.052468,10.070695
2,01004,14288.0,804.651500,14022.0,743.288479,2877.907354,2326.327150,20510.0,19554.000000,0.018792,0.201421,0.165906,0.035516,0.056317,0.053009,0.003308,9.880935,9.928668
3,01005,1782.0,115.000000,1627.0,105.518839,377.000000,281.383570,24050.0,22387.619048,0.090999,0.211560,0.172946,0.038614,0.064534,0.064855,-0.000321,10.016263,10.087890
5,01007,2827.0,211.204367,2570.0,195.000000,621.371086,497.000000,23380.0,21650.666667,0.095310,0.219799,0.193385,0.026414,0.074710,0.075875,-0.001166,9.982792,10.059636
6,01008,768.0,50.394579,743.0,71.903226,174.957312,157.787634,25450.0,23669.523810,0.033094,0.227809,0.212366,0.015443,0.065618,0.096774,-0.031156,10.071944,10.144471
7,01009,324.0,4.773479,338.0,16.047478,75.583346,65.192878,23790.0,21486.250000,-0.042302,0.233282,0.192878,0.040404,0.014733,0.047478,-0.032745,9.975168,10.077021
8,01010,1101.0,44.135561,1142.0,42.731525,148.517862,129.262862,23770.0,21015.333333,-0.036562,0.134894,0.113190,0.021704,0.040087,0.037418,0.002669,9.953008,10.076180
9,01011,368.0,34.615852,397.0,70.119481,83.427877,83.524675,24450.0,22690.000000,-0.075853,0.226706,0.210390,0.016317,0.094065,0.176623,-0.082559,10.029680,10.104385
10,01012,327.0,4.986798,325.0,33.440514,64.200351,66.881029,21070.0,20211.000000,0.006135,0.196331,0.205788,-0.009456,0.015250,0.102894,-0.087644,9.913982,9.955606
11,01013,143.0,9.930556,157.0,7.850000,16.881944,18.643750,19900.0,19534.285714,-0.093401,0.118056,0.118750,-0.000694,0.069444,0.050000,0.019444,9.879926,9.898475
12,01014,3336.0,94.883670,3405.0,153.502860,460.334521,384.881108,21460.0,19565.714286,-0.020472,0.137990,0.113034,0.024956,0.028442,0.045082,-0.016639,9.881534,9.973946
13,01015,663.0,82.376950,638.0,24.399073,150.656243,116.473730,22700.0,21587.142857,0.038437,0.227234,0.182561,0.044673,0.124249,0.038243,0.086006,9.979853,10.030120
14,01016,458.0,15.000000,440.0,19.426049,75.000000,59.249448,21840.0,20532.500000,0.040094,0.163755,0.134658,0.029098,0.032751,0.044150,-0.011399,9.929764,9.991498
15,01017,445.0,0.000000,427.0,4.874429,75.560119,52.643836,20120.0,18644.761905,0.041290,0.169798,0.123288,0.046510,0.000000,0.011416,-0.011416,9.833321,9.909470
17,01021,1490.0,141.581345,1376.0,99.237497,356.365055,276.859922,24810.0,22960.666667,0.079595,0.239171,0.201206,0.037965,0.095021,0.072120,0.022901,10.041538,10.119002
18,01022,1213.0,41.185678,1193.0,30.253051,201.204758,144.651970,20690.0,18782.000000,0.016625,0.165874,0.121251,0.044623,0.033954,0.025359,0.008595,9.840654,9.937406
20,01024,3299.0,192.812225,3386.0,152.424437,627.638989,535.663023,22820.0,21300.555556,-0.026030,0.190251,0.158199,0.032052,0.058446,0.045016,0.013430,9.966488,10.035393
21,01025,4068.0,205.506844,3177.0,115.000000,798.923501,553.000000,22970.0,21148.625000,0.247214,0.196392,0.174064,0.022329,0.050518,0.036198,0.014320,9.959330,10.041944
22,01026,977.0,55.256873,881.0,20.000000,150.747654,120.000000,21060.0,20546.000000,0.103429,0.154296,0.136209,0.018088,0.056558,0.022701,0.033856,9.930422,9.955131

In [92]:
# CHARGEMENT ELECTIONS


# VERIFIER bien CODE NUANCE et pas NUANCE LISTE
df_elec_14 = pd.read_csv(os.path.join(RAW_ELEC_DIR, 'elec_2014_all.csv'), dtype={'Code commune': str})
df_elec_20 = pd.read_csv(os.path.join(RAW_ELEC_DIR, 'elec_2020_all.csv'), dtype={'Code commune': str})


# Renommer si nécessaire (verifier Code Nuance)
df_elec_14 = df_elec_14.rename(columns={'Code commune': 'COM'})
df_elec_20 = df_elec_20.rename(columns={'Code commune': 'COM'})

# DÉFINITION DU BLOC GAUCHE + ÉCOLOS 

BLOC_GAUCHE = [
    'LVECE', 'LVEC', 'LECO',         # Écolos
    'LUG', 'LDVG', 'LSOC', 'LFI',    # Gauche diverse, PS, LFI
    'LGEN', 'LCOM', 'LRDG', 'LGRA', 'LPG' # PCF, Front de gauche, etc.
]

# Idée: mettr à 0 le score si pas de liste de gauche. C'est fait plus bas lors du merge

def calcul_score_bloc(df_elec, nuances_bloc, annee):
    """Calcule la somme des voix du bloc pour chaque commune."""
    # Filtrer les nuances du bloc (gauche dans notre cas)
    mask = df_elec['Code Nuance'].isin(nuances_bloc)
    df_filtered = df_elec[mask].copy()
    
    # Sommer par commune (cas où il y a >=2 listes de gauche)
    scores = df_filtered.groupby('COM')['% Voix/Exp'].sum().reset_index()
    scores.rename(columns={'% Voix/Exp': f'score_gauche_{annee}'}, inplace=True)
    return scores

# appel a la fction, calcul des scores
score_14 = calcul_score_bloc(df_elec_14, BLOC_GAUCHE, '2014')
score_20 = calcul_score_bloc(df_elec_20, BLOC_GAUCHE, '2020')

print("Scores calculés.")

Scores calculés.

In [93]:
# On part de la base socio-demo (qui contient toutes les communes)
df_final = df_socio.copy()

# On colle les scores 2014
df_final = df_final.merge(score_14, on='COM', how='left')

# On colle les scores 2020
df_final = df_final.merge(score_20, on='COM', how='left')

# CRUCIAL pour la regression: Remplacer les NaN par 0
# Si pas de correspondance, ça veut dire 0 voix pour la gauche
df_final['score_gauche_2014'] = df_final['score_gauche_2014'].fillna(0)
df_final['score_gauche_2020'] = df_final['score_gauche_2020'].fillna(0)

# Calcul du DELTA SCORE (Variable Y)
df_final['delta_score_gauche'] = df_final['score_gauche_2020'] - df_final['score_gauche_2014']

# Log population
# On le calcule ici tant que la population est brute (positive)
df_final['log_pop_2020'] = np.log(df_final['pop_2020'])
df_final['log_pop_2014'] = np.log(df_final['pop_2014'])

# Sélection des colonnes (pour R par exemple, analyse faite en R temporairement)
cols_export = [
    'COM',
    'score_gauche_2014',  
    'score_gauche_2020', 
    'delta_score_gauche',
    'pop_2014',
    'pop_2020', 
    'log_pop_2014',
    'log_pop_2020',
    'croissance_pop', 
    'pct_sup_2014',
    'pct_sup_2020',
    'delta_pct_diplome', 
    'pct_cadres_2014',
    'pct_cadres_2020',  
    'delta_pct_cadres', 
    'med_2013',
    'med_2019',   
    'log_med_13',
    'log_med_19' 

]

# On retire les lignes avec des NaN dans les variables explicatives (Socio-demo manquantes)
# faire analyse des données perdues ? 
df_export = df_final[cols_export].dropna()

print(f"Base finale prête : {len(df_export)} communes.")
print(df_export.head())

Base finale prête : 31069 communes.
     COM  score_gauche_2014  score_gauche_2020  delta_score_gauche  pop_2014  \
0  01001               0.00                0.0                0.00     767.0
1  01002               0.00                0.0                0.00     239.0
2  01004              38.69                0.0              -38.69   14022.0
3  01005               0.00                0.0                0.00    1627.0
4  01007              46.78                0.0              -46.78    2570.0

   pop_2020  log_pop_2014  log_pop_2020  croissance_pop  pct_sup_2014  \
0     806.0      6.642487      6.692084        0.049597      0.183833
1     262.0      5.476464      5.568345        0.091881      0.251029
2   14288.0      9.548383      9.567175        0.018792      0.165906
3    1782.0      7.394493      7.485492        0.090999      0.172946
4    2827.0      7.851661      7.946971        0.095310      0.193385

   pct_sup_2020  delta_pct_diplome  pct_cadres_2014  pct_cadres_2020  \
0      0.224666           0.040832         0.097784         0.076643
1      0.307261           0.056232         0.061728         0.069785
2      0.201421           0.035516         0.053009         0.056317
3      0.211560           0.038614         0.064855         0.064534
4      0.219799           0.026414         0.075875         0.074710

   delta_pct_cadres      med_2013  med_2019  log_med_13  log_med_19
0         -0.021141  22130.000000   23970.0   10.004689   10.084558
1          0.008057  23213.000000   23640.0   10.052468   10.070695
2          0.003308  19554.000000   20510.0    9.880935    9.928668
3         -0.000321  22387.619048   24050.0   10.016263   10.087890
4         -0.001166  21650.666667   23380.0    9.982792   10.059636

Problème majeur: la politique n'est pas forcément bien "structurée" pour toutes les communes, notamment pas pour les communes de peu d'habitants. Ainsi l'analyse ne peut proter que sur les communes dont la politique est "structurée": elle ne represente donc pas une étude poltiique de toute la France.

In [94]:
# On crée un filtre : au moins un score > 0 en 2014 OU en 2020 
filter_structural = (df_final['score_gauche_2014'] > 0) | (df_final['score_gauche_2020'] > 0)

# On filtre
df_reg = df_final[filter_structural].copy()

print(f"Nombre de communes pour la régression : {df_reg.shape[0]}")

Nombre de communes pour la régression : 1533

In [95]:
print(31069-1533,"communes sont exclues de l'analyse car politique jugée pas assez structurée pour une régression viable.", "Il reste donc",1533,"communes pour l'analyse.")

29536 communes sont exclues de l'analyse car politique jugée pas assez structurée pour une régression viable. Il reste donc 1533 communes pour l'analyse.

Regarder aussi communes de plus de "arbitraire,1500-3500" habs pour analyse socio pertinente ? Regarder présidentielles ?

Cellule de visualisation (réservée aux .head() ) pour vérifier la cohérence

In [96]:
df_reg.head()

,COM,pop_2020,cadres_nb_2020,pop_2014,cadres_nb_2014,sup_nb_2020,sup_nb_2014,med_2019,med_2013,croissance_pop,...,pct_cadres_2020,pct_cadres_2014,delta_pct_cadres,log_med_13,log_med_19,score_gauche_2014,score_gauche_2020,delta_score_gauche,log_pop_2020,log_pop_2014
2,01004,14288.0,804.651500,14022.0,743.288479,2877.907354,2326.327150,20510.0,19554.000000,0.018792,...,0.056317,0.053009,0.003308,9.880935,9.928668,38.69,0.0,-38.69,9.567175,9.548383
4,01007,2827.0,211.204367,2570.0,195.000000,621.371086,497.000000,23380.0,21650.666667,0.095310,...,0.074710,0.075875,-0.001166,9.982792,10.059636,46.78,0.0,-46.78,7.946971,7.851661
27,01034,9207.0,355.820237,8983.0,338.455942,1741.814595,1498.801418,20030.0,18549.000000,0.024630,...,0.038647,0.037677,0.000969,9.828171,9.904986,48.83,0.0,-48.83,9.127719,9.103089
135,01160,10612.0,1426.479025,9337.0,1498.179206,3958.008204,3348.661633,26770.0,25508.333333,0.128000,...,0.134421,0.160456,-0.026035,10.146760,10.195037,49.55,0.0,-49.55,9.269741,9.141740
152,01185,4824.0,222.006184,3829.0,87.627697,1116.548642,642.483616,21990.0,20198.148148,0.231000,...,0.046021,0.022885,0.023136,9.913346,9.998343,38.72,0.0,-38.72,8.481359,8.250359

probleme de doublons communes

In [97]:
# resolution problème doublons communes (pas de problème ici en fait)

STANDARDISATION (ne changera ni le R^2n ni les t-values, ni les p-values,  mais rendra les coeffs beaucoup plus faciles à interpréter) (rendra les coeffs corrects surtout!) méthode: Z-score.

C EST EN COURS: pour l'instant ça change le tableau statsmodel alors que ç ne devrais pas.

In [98]:
# Standardisation des variables (X seulement)


df_std = df_reg.copy()

# 1. On liste ce qu'on NE VEUT PAS toucher (Variable Cible Y + Identifiants)
# On garde Y naturel pour dire "ça augmente le vote de X points"
cols_excluded = ['COM', 'score_gauche_2014', 'score_gauche_2020', 'delta_score_gauche']

# 2. On récupère automatiquement toutes les autres variables numériques (les X)
# Cela inclura : croissance_pop, delta_pct_cadres, log_med_13, etc.
x_vars = [c for c in df_std.select_dtypes(include=['float', 'int']).columns if c not in cols_excluded]

print("Variables transformées (X) :", x_vars)
print("Variables conservées naturelles (Y) :", cols_excluded)

# 3. Standardisation (Z-score) des X
for col in x_vars:
    if df_std[col].std() != 0: # Sécurité
        df_std[col] = (df_std[col] - df_std[col].mean()) / df_std[col].std()

# 4. Export
output_std_path = os.path.join(MERGED_DATA_DIR, 'data_regression_std.csv')
df_std.to_csv(output_std_path, index=False, sep=',', encoding='utf-8', na_rep='NA')

print(f"Fichier prêt pour l'analyse : {output_std_path}")

Variables transformées (X) : ['pop_2020', 'cadres_nb_2020', 'pop_2014', 'cadres_nb_2014', 'sup_nb_2020', 'sup_nb_2014', 'med_2019', 'med_2013', 'croissance_pop', 'pct_sup_2020', 'pct_sup_2014', 'delta_pct_diplome', 'pct_cadres_2020', 'pct_cadres_2014', 'delta_pct_cadres', 'log_med_13', 'log_med_19', 'log_pop_2020', 'log_pop_2014']
Variables conservées naturelles (Y) : ['COM', 'score_gauche_2014', 'score_gauche_2020', 'delta_score_gauche']
Fichier prêt pour l'analyse : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/merged/data_regression_std.csv

In [99]:

#export des données brutes non standardisées

output_filename = 'data_regression.csv'
output_path = os.path.join(MERGED_DATA_DIR, output_filename)

df_reg.to_csv(
    output_path, 
    index=False, 
    sep=',', 
    encoding='utf-8', 
    na_rep='NA' # Pour compatibilité R
)

print(f"Fichier exporté avec succès : {output_path}")

Fichier exporté avec succès : /Users/romain/Desktop/Projets DS/Python-project/notebooks/../data/merged/data_regression.csv